### ISSUE TITLE
first mul, then div. Is this a bug?

### ISSUE THREAD

**Issue by zgfzgf** [Uniswap/uniswap-v3-core-optimism#8]
(atOrAfter.tickCumulative - beforeOrAt.tickCumulative) *  targetDelta / observationTimeDelta

corresponding L283
    
https://github.com/Uniswap/uniswap-v3-core-optimism/blob/da89f9b88a1616be1ef075ad4313e8aeb3532906/contracts/libraries/Oracle.sol#L276-L284

**Comment by moodysalem** [comment]
it is correct. `(atOrAfter.tickCumulative - beforeOrAt.tickCumulative) % observationTimeDelta == 0` is an invariant tested in the echidna tests, so division before multiplication is safe.

**Comment by zgfzgf** [comment]
I see.  tick == (atOrAfter.tickCumulative - beforeOrAt.tickCumulative) / observationTimeDelta
I think. may should test it. @moodysalem
